blueprint:
  name: Escada Inteligente com WLED (Subir / Descer)
  description: >
    Controle de escada com WLED usando dois sensores de presença,
    trava de direção, liberação segura, timeout de segurança
    e modo de funcionamento (sempre / dia / noite).
  domain: automation

  input:
    sensor_inferior:
      name: Sensor Inferior
      selector:
        entity:
          domain: binary_sensor

    sensor_superior:
      name: Sensor Superior
      selector:
        entity:
          domain: binary_sensor

    luz_escada:
      name: Luz / WLED
      selector:
        entity:
          domain: light

    seletor_efeito:
      name: Seletor de Efeito do WLED
      selector:
        entity:
          domain: select

    efeito_subir:
      name: Nome do efeito de subida
      description: Deve ser exatamente o nome do efeito no WLED
      selector:
        text:

    efeito_descer:
      name: Nome do efeito de descida
      description: Deve ser exatamente o nome do efeito no WLED
      selector:
        text:

    direcao_helper:
      name: Helper de Direção
      description: Input_select com as opções - livre, subida, descida
      selector:
        entity:
          domain: input_select

    tempo_timeout:
      name: Timeout de segurança (segundos)
      default: 15
      selector:
        number:
          min: 5
          max: 120
          unit_of_measurement: s

    modo_funcionamento:
      name: Modo de Funcionamento
      default: sempre
      selector:
        select:
          options:
            - label: Sempre ativo
              value: sempre
            - label: Apenas à noite
              value: noite
            - label: Apenas de dia
              value: dia

mode: restart

variables:
  direcao: !input direcao_helper
  modo: !input modo_funcionamento
  sensor_inf: !input sensor_inferior
  sensor_sup: !input sensor_superior
  timeout_seg: !input tempo_timeout

trigger:
  - platform: state
    entity_id: !input sensor_inferior
    to: "on"
    id: subir

  - platform: state
    entity_id: !input sensor_superior
    to: "on"
    id: descer

  - platform: state
    entity_id: !input sensor_inferior
    to: "off"
    id: sensores_off

  - platform: state
    entity_id: !input sensor_superior
    to: "off"
    id: sensores_off

condition:
  - condition: template
    value_template: >
      {{ trigger.id == 'sensores_off'
         or states(direcao) == 'livre'
         or (states(direcao) == 'subida' and trigger.id == 'subir')
         or (states(direcao) == 'descida' and trigger.id == 'descer') }}

  - condition: template
    value_template: >
      {% set noite = state_attr('sun.sun', 'elevation') is not none
         and state_attr('sun.sun', 'elevation') < 0 %}
      {{ modo == 'sempre'
         or (modo == 'noite' and noite)
         or (modo == 'dia' and not noite) }}

action:
  - choose:

      # ========= SUBIR =========
      - conditions:
          - condition: trigger
            id: subir
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input direcao_helper
            data:
              option: subida

          - service: light.turn_on
            target:
              entity_id: !input luz_escada

          - service: select.select_option
            target:
              entity_id: !input seletor_efeito
            data:
              option: !input efeito_subir

          - wait_template: "{{ is_state(sensor_inf, 'off') and is_state(sensor_sup, 'off') }}"
            timeout:
              seconds: "{{ timeout_seg }}"
            continue_on_timeout: true

      # ========= DESCER =========
      - conditions:
          - condition: trigger
            id: descer
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input direcao_helper
            data:
              option: descida

          - service: light.turn_on
            target:
              entity_id: !input luz_escada

          - service: select.select_option
            target:
              entity_id: !input seletor_efeito
            data:
              option: !input efeito_descer

          - wait_template: "{{ is_state(sensor_inf, 'off') and is_state(sensor_sup, 'off') }}"
            timeout:
              seconds: "{{ timeout_seg }}"
            continue_on_timeout: true

      # ========= FINALIZAÇÃO SEGURA =========
      - conditions:
          - condition: trigger
            id: sensores_off
          - condition: template
            value_template: "{{ is_state(sensor_inf, 'off') and is_state(sensor_sup, 'off') }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input luz_escada

          - service: input_select.select_option
            target:
              entity_id: !input direcao_helper
            data:
              option: livre
